default:
  image: node:14

  before_script:
    - export NODE_ENV=development
    - npm install

stages:
  - lint
  - test

lint-job:
  stage: lint
  script:
    - npm run lint -- scripts
  timeout: 5m

test-job:
  stage: test
  script:
    - npm test
  artifacts:
    when: always
    reports:
      junit:
        - junit.xml
  timeout: 5m
