---
version: '3'
services:
  redis:
    image: ${REDIS_IMAGE:-redis:4-stretch}

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      - discovery.type=single-node
